🚸 add user check before continue check
C0casio45/bot_onet pull request #83
Opened 2022-06-02 13:05 UTC by C0casio45

NOT YET TESTED

2022-06-03 23:28 UTC, Netinq requested changes

2022-06-03 23:28 UTC, Netinq commented on commands/ban.js
> +    function onError() {
La fonction doit être async
```suggestion
    async function onError() {
```

2022-06-03 23:28 UTC, Netinq commented on bot_modules/faceit.js
> +        req.on("error", (error) => callback(true, error));
Tu fais appel à un callback qui n'est pas déclaré.

2022-06-03 23:28 UTC, Netinq commented on bot_modules/faceit.js
> +        callback(true, exception);
Tu fais appel à un callback qui n'est pas déclaré.

2022-06-22 12:32 UTC, C0casio45 commented
trop vieux

2022-06-22 12:32 UTC, closed without merging